### ISSUE TITLE
Crash on server.

### ISSUE THREAD

**Issue by Taknax** [illusivesoulworks/elytrautilities#6]
I have a crash in my server. I use MC 1.19.2 wih Forge 43.2.4. I let you the crashlog here.
[crash-2023-02-20_23.40.45-fml.txt](https://github.com/illusivesoulworks/elytrautilities/files/10788404/crash-2023-02-20_23.40.45-fml.txt)

**Comment by TheIllusiveC4** [comment]
This mod is client-side only, it should not be installed on dedicated servers.
